### ISSUE TITLE
Pipeline configuration

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-user-service#12]
## Issue Description
Create a new service on docker-compose to run the pipeline. The pipeline should build the project, run the pylint and run tests and generate a response to the user.

## Tasks:
- [ ] Add the technologies used in the project.
- [ ] Fix pylint errors, if needed.
- [ ] Add to docker-compose.
- [ ] Update README.md
