### ISSUE TITLE
User filter for occurrence and neighborhood rating

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#14]
## Issue Description
Implement filter to catch all occurrences and all ratings of a specific user in the respective "get all" endpoints

## Tasks:
- [x] Get occurrences by user
- [x] Get ratings by user
- [x] hide username in gets from occurrences
- [x] update unitary tests
