### ISSUE TITLE
Filters for occurrence types and updating the types

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#28]
## Issue Description
Make filters for occurrence types and updating the types allowed

## Tasks:
- [x] Add the types "Furto a Transeunte" and "Furto de Veículo" to occurrence_type field
- [x] Update the validations of occurrence_type field
- [x] Add filter for each type of occurrence in this endpoint: 
https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/blob/83adbd6df2b078a9e2b88ceb4607ea436c0c0ac8/src/views/occurrence.py#L23
- [ ] Allow more than one to be received in the same request
- [x] It is possible to pass more than one type in the same request
- [x] Validate the filters allowed
- [x] Update the swagger with the filters
- [x] Update the tests, if necessary
