### ISSUE TITLE
Get neighborhood list

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#30]
## Issue Description
Get a list of neighborhoods in the states. At the moment the most priority states are DF and São Paulo.
Find a source with the list and a way to insert it into the bank. The neighborhood model can be updated if necessary.

## Suggestion
I found this [repository](https://github.com/chandez/Estados-Cidades-IBGE) that there is a SQL script for inserting neighborhoods of all municipalities, but there are no neighborhoods of DF. The owner of the repository used the [SIDRA](https://sidra.ibge.gov.br/territorio) system to obtain the neighborhoods, giving research on this system I found [this list](https://sidra.ibge.gov.br/territorio#/N18/IN%20N3%2053) that seems to be the neighborhoods of DF. So, I believe that this repository and this system are useful for obtaining the neighborhoods we need

## Tasks:
- [x] Decide from where and how neighborhoods will be obtained
- [x] Update the neighborhood model if necessary
- [x] Create a SQL script for inserting neighborhoods
