### ISSUE TITLE
Average of the rating of neighborhoods

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#31]
## Issue Description
Return, at the endpoint of getting one neighborhood, the simple average rating of the neighborhood and the classification of its characteristics.

In the answer JSON, you should have the neighborhood information, the average rating and a rating for the details.

## Classification of rating characteristics/details
A neighborhood feature can have 3 classifications which will be the integers 1, 2 and 3, each integer of that neighborhood will represent a color in the front end.

To obtain this integer, obtain the total T of the characteristic (total positive + total negative). Get from T the percentage P of positives, if that percentage is below 40 the classification C will be 1, if it is between 40 and 70 it will be 2, if it was above or equal to 70 it will be 3.
What should be returned in the response is the value of C

Exemple:
T = 10 votes in good lighting + 10 votes in bad lighting = 20
P = 50%, considering that 50% of T was good lighting
C = 2, because 40 < P <70
so, in response json --> "lighting": 2
 
## Tasks:
- [x] Implement endpoint of getting one neighborhood
- [x] Calculate the average of ratings for a neighborhood
- [x] Calculate the classification of each characteristic of a neighborhood
- [x] Implement tests for calculations
- [x] Update Swagger
