### ISSUE TITLE
Correct the rating model and make the necessary adaptations

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#37]
## Issue Description
Correct the rating model so that it has the following fields:
```
id_rating = Column(Integer, primary_key=True)
user = Column(String, ForeignKey(User.username))
id_neighborhood = Column(Integer, ForeignKey(Neighborhood.id_neighborhood))
rating_neighborhood = Column(Integer, nullable=False)
lighting = Column(Boolean)
movement_of_people = Column(Boolean)
police_rounds = Column(Boolean)
```
Then, all the code that uses this model will have to be adapted: Post, update, tests, calculation of statistics, validations, etc. 
The fields lighting, movement_of_people and police_rounds are not required.

## Tasks:
- [x] Update rating model
- [x] Update rating post and patch and the respective validations
- [x] Update statistic calculus of neighborhoods
- [x] Update tests
- [x] Update swagger
