### ISSUE TITLE
User protection improvements

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#38]
## Issue Description
Currently, it is possible for a user to edit and delete occurrences and evaluations of other users, he is just logged in. Changes must be made so that this is no longer possible.
In addition, despite the users' password being encrypted, it is not good that it is being returned on get.

## Tasks:
- [x] Prohibit editing and deleting occurrences of any user who is not logged in
- [x] Prohibit editing and deleting ratings of any user who is not logged in
- [x] Omit user password on get
- [x] Make/update tests
