### ISSUE TITLE
Creating, reading and deleting favorite places

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#39]
## Issue Description
Implement creating, reading and deleting favorite user locations. The update method will not be necessary.
For reading, only the get by user endpoint is required.
The necessary endpoints must be protected with authentication and it should not be possible for a user to tamper with another user's favorite locations.

## Model of favorite places
The relationship between the favorite place table and user table is 1 to N, that is, a user can have N favorite places.
The model attributes will be:
* string user, the foreign key with the username of the user
* integer id_place, foreign with the id of place
* float latitude
* float longitude

All the fields are required.

## Tasks:
- [x] Implement the model
- [x] Implement post endpont
- [x] Implement delete endpoint
- [x] Implement get by user endpoint
- [x] Protect the endpoints
- [x] Make tests
- [x] Update swagger
