### ISSUE TITLE
Create an instance of  database to use on tests 

### ISSUE THREAD

**Issue by lboaventura25** [fga-eps-mds/2020.1-stay-safe-user-service#45]
## Issue Description
Create an instance of  database to use on tests.

## Tasks:
- [ ] Search how to create an instance of databse on sqlalchemy.
- [ ] Implement the feature
- [ ] Test if other features still working and tests passed.
