### ISSUE TITLE
Add name field to favorite place

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#49]
## Issue Description
Add the name field to the favorite location model. The field must be a maximum length string of 30.
The rest of the code that deals with the model must be updated, such as the tests and post method validations.

## Tasks:
- [x] Update the model
- [x] Update the post method validations
- [x] Update the tests
- [x] Update swagger
