### ISSUE TITLE
Implement business rules in the occurrence functionality

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#50]
## Issue Description
Implement the following business rules in the occurrence functionality:

### Limit occurrence register
A user can only register 5 occurrences in 7 days.

### Limit editing time for an occurrence
An occurrence can only be edited up to 3 months after its registration.

### Occurrence in the last 12 months
The occurrences recovered in the get must be the last 12 months. No filter should be implemented in the get endpoint, the occurrences must be retrieved from the database as well

## Tasks:
- [x] Limit occurrence registe
- [x] Limit editing time for an occurrence
- [x] Occurrence in the last 12 months
- [x] Implement tests
