### ISSUE TITLE
Setup Sonarqube

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-user-service#54]
## Issue Description
Setup Sonarqube to make a code scan in the repository

## Tasks:
- [ ] Search how to use Sonarqube
- [ ] Setup Sonarqube scan
- [ ] Update readme with all the instructions
