### ISSUE TITLE
Improve return messages

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#60]
## Issue Description
It is necessary to standardize the language used in the requests' return messages (both for the success case and for the error case). I suggest that the default language is Portuguese so that the front does not need to translate messages. 

It is necessary to handle errors that refer to a unique constraint violation so that SQL errors do not arrive at the front (ex: when trying to register a user with a username or with an email that already exists in the bank):
![image](https://user-images.githubusercontent.com/30883179/99263861-7c913680-27fe-11eb-834e-e0865cc2df7f.png)

You will need to update the tests for new messages.

## Tasks:
- [x] Standardize the language of messages
- [x] Handle errors that refer to a unique constraint violation
- [x] Update the tests
