### ISSUE TITLE
Improve name of some types of occurrences

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#61]
## Issue Description
In order to improve communication with the user, the need to use more popular names in the types of occurrences was raised.
So in the types of "Roubo a Transeunte" and "Furto a Transeunte", changing the word "Transeunte" for "Pedestre".
After this change, it will be necessary to update the tests and corresponding validations.

## Tasks:
- [x] Update the types on occurence model
- [x] Update the corresponding validations
- [x] Update the conrrespoding tests
- [x] Update the swagger if necessary
