### ISSUE TITLE
Notification of favorite places

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-user-service#65]
## Issue Description
Implement a routine to notify when an occurrence has been registered near users' favorite locations. For the routine to be faster try to make this implementation asynchronous.
Notification should only reach a user when other users' occurrences are registered, that is, it should not be notified when the user himself registers an occurrence near one of his favorite places.
Information about the occurrence being reported must be sent to the front, at least the id, so that the user can view that occurrence.
It is also necessary to add in the user model a flag that says whether the user wants to receive this notification or not.  The default value of this flag can be true. So this implementation is to take this flag into account.

## How it will be validated
To validate the issue the following tests will be done:

- The reviewer will create two users, in the first user he will register a favorite place. On the second user it will register an occurrence within the radius near the favorite location of the first user. Notification is expected to arrive for the first user.
- The reviewer will create an occurrence on the first user near a favorite location of the same user. It is expected that this user will not be notified
- The reviewer will set the first user's notification flag as false and will repeat the first test, it is expected that he will not receive the notification.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Update user model with flag of notification
- [x] Update the PATCH method with the new flag
- [x] Define the distance that will be considered close to the favorite place
- [x] Implement routine to check if the occurrence is close to some favorite place
- [x] Restrict notifications only when the occurrence has been registered by another user
- [x] Restrict notifications only to users who have the flag set to true 
- [x] Return to the front which occurrence is being registered
- [x] Update tests if necessary
- [ ] Update swagger if has a new endpoint

**Comment by lboaventura25** [comment]
We decided that the distance of an occurrence to be considered near to a favorite place is at least 1km. What do you think, @silvasara?

**Comment by silvasara** [comment]
@lboaventura25 It's great.
